{
  imports = [
    ./user.nix
    ./home.nix
    ./security.nix
    ./impermanence.nix
    ./system/nix.nix
    ./system/locale.nix
    ./system/pipewire.nix
    ./system/bluetooth.nix
    ./system/networkmanager.nix
    ./system/tailscale.nix
    ./desktops/dwm
    ./desktops/dwl
    ./desktops/hyprland
    ./apps/git.nix
    ./apps/bash.nix
    ./apps/ssh.nix
    ./apps/gpg.nix
    ./apps/direnv.nix
    ./apps/helix.nix
    ./apps/develop.nix
    ./apps/firefox.nix
    ./apps/discord.nix
    ./apps/slack.nix
    ./apps/spotify.nix
    ./apps/steam.nix
    ./apps/podman.nix
    ./apps/common.nix
    ./apps/ghostty.nix
  ];
}
